/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package sh.ory.client-kotlin-multiplatform.models

import io.kotlintest.shouldBe
import io.kotlintest.specs.ShouldSpec

import sh.ory.client-kotlin-multiplatform.models.SelfServiceFlowExpiredError
import sh.ory.client-kotlin-multiplatform.models.GenericError

class SelfServiceFlowExpiredErrorTest : ShouldSpec() {
    init {
        // uncomment below to create an instance of SelfServiceFlowExpiredError
        //val modelInstance = SelfServiceFlowExpiredError()

        // to test the property `error`
        should("test error") {
            // uncomment below to test the property
            //modelInstance.error shouldBe ("TODO")
        }

        // to test the property `expiredAt` - When the flow has expired
        should("test expiredAt") {
            // uncomment below to test the property
            //modelInstance.expiredAt shouldBe ("TODO")
        }

        // to test the property `since` - A Duration represents the elapsed time between two instants as an int64 nanosecond count. The representation limits the largest representable duration to approximately 290 years.
        should("test since") {
            // uncomment below to test the property
            //modelInstance.since shouldBe ("TODO")
        }

        // to test the property `useFlowId` - The flow ID that should be used for the new flow as it contains the correct messages.
        should("test useFlowId") {
            // uncomment below to test the property
            //modelInstance.useFlowId shouldBe ("TODO")
        }

    }
}
