# NOTE: This file is auto generated by OpenAPI Generator 7.12.0 (https://openapi-generator.tech).
# Do not edit this file manually.

defmodule Ory.Model.ContinueWithDeviceAuthnPinEntryUi do
  @moduledoc """
  The enrolled key's client_key_id is not included: it is the SHA-256 fingerprint of the device's own public key, which the device derives locally. Non-PIN keys need no client action at all and therefore produce no continue_with.
  """

  @derive Jason.Encoder
  defstruct [
    :action,
    :data
  ]

  @type t :: %__MODULE__{
    :action => String.t,
    :data => Ory.Model.ContinueWithDeviceAuthnPinEntryUiData.t
  }

  alias Ory.Deserializer

  def decode(value) do
    value
     |> Deserializer.deserialize(:data, :struct, Ory.Model.ContinueWithDeviceAuthnPinEntryUiData)
  end
end

