# NOTE: This file is auto generated by OpenAPI Generator 6.6.0 (https://openapi-generator.tech).
# Do not edit this file manually.

defmodule Ory.Model.UpdateVerificationFlowBody do
  @moduledoc """
  Update Verification Flow Request Body
  """

  @derive [Poison.Encoder]
  defstruct [
    :csrf_token,
    :email,
    :method,
    :code
  ]

  @type t :: %__MODULE__{
    :csrf_token => String.t | nil,
    :email => String.t,
    :method => String.t,
    :code => String.t | nil
  }
end

defimpl Poison.Decoder, for: Ory.Model.UpdateVerificationFlowBody do
  def decode(value, _options) do
    value
  end
end

