# NOTE: This file is auto generated by OpenAPI Generator 7.7.0 (https://openapi-generator.tech).
# Do not edit this file manually.

defmodule Ory.Model.IdentityCredentialsPassword do
  @moduledoc """
  
  """

  @derive Jason.Encoder
  defstruct [
    :hashed_password
  ]

  @type t :: %__MODULE__{
    :hashed_password => String.t | nil
  }

  def decode(value) do
    value
  end
end

