/*
 * Ory APIs
 *
 * Documentation for all public and administrative Ory APIs. Administrative APIs can only be accessed with a valid Personal Access Token. Public APIs are mostly used in browsers. 
 *
 * The version of the OpenAPI document: v0.0.1-alpha.82
 * Contact: support@ory.sh
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using Ory.Client.Api;
using Ory.Client.Model;
using Ory.Client.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace Ory.Client.Test.Model
{
    /// <summary>
    ///  Class for testing ClientSubmitSelfServiceSettingsFlowWithTotpMethodBody
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class ClientSubmitSelfServiceSettingsFlowWithTotpMethodBodyTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for ClientSubmitSelfServiceSettingsFlowWithTotpMethodBody
        //private ClientSubmitSelfServiceSettingsFlowWithTotpMethodBody instance;

        public ClientSubmitSelfServiceSettingsFlowWithTotpMethodBodyTests()
        {
            // TODO uncomment below to create an instance of ClientSubmitSelfServiceSettingsFlowWithTotpMethodBody
            //instance = new ClientSubmitSelfServiceSettingsFlowWithTotpMethodBody();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of ClientSubmitSelfServiceSettingsFlowWithTotpMethodBody
        /// </summary>
        [Fact]
        public void ClientSubmitSelfServiceSettingsFlowWithTotpMethodBodyInstanceTest()
        {
            // TODO uncomment below to test "IsType" ClientSubmitSelfServiceSettingsFlowWithTotpMethodBody
            //Assert.IsType<ClientSubmitSelfServiceSettingsFlowWithTotpMethodBody>(instance);
        }


        /// <summary>
        /// Test the property 'CsrfToken'
        /// </summary>
        [Fact]
        public void CsrfTokenTest()
        {
            // TODO unit test for the property 'CsrfToken'
        }
        /// <summary>
        /// Test the property 'Method'
        /// </summary>
        [Fact]
        public void MethodTest()
        {
            // TODO unit test for the property 'Method'
        }
        /// <summary>
        /// Test the property 'TotpCode'
        /// </summary>
        [Fact]
        public void TotpCodeTest()
        {
            // TODO unit test for the property 'TotpCode'
        }
        /// <summary>
        /// Test the property 'TotpUnlink'
        /// </summary>
        [Fact]
        public void TotpUnlinkTest()
        {
            // TODO unit test for the property 'TotpUnlink'
        }

    }

}
