/*
 * ORY Keto
 *
 * A cloud native access control server providing best-practice patterns (RBAC, ABAC, ACL, AWS IAM Policies, Kubernetes Roles, ...) via REST APIs.
 *
 * The version of the OpenAPI document: v0.0.0
 * Contact: hi@ory.sh
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using Ory.Keto.Client.Api;
using Ory.Keto.Client.Model;
using Ory.Keto.Client.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace Ory.Keto.Client.Test.Model
{
    /// <summary>
    ///  Class for testing KetoListOryAccessControlPolicyRoles
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class KetoListOryAccessControlPolicyRolesTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for KetoListOryAccessControlPolicyRoles
        //private KetoListOryAccessControlPolicyRoles instance;

        public KetoListOryAccessControlPolicyRolesTests()
        {
            // TODO uncomment below to create an instance of KetoListOryAccessControlPolicyRoles
            //instance = new KetoListOryAccessControlPolicyRoles();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of KetoListOryAccessControlPolicyRoles
        /// </summary>
        [Fact]
        public void KetoListOryAccessControlPolicyRolesInstanceTest()
        {
            // TODO uncomment below to test "IsType" KetoListOryAccessControlPolicyRoles
            //Assert.IsType<KetoListOryAccessControlPolicyRoles>(instance);
        }


        /// <summary>
        /// Test the property 'Flavor'
        /// </summary>
        [Fact]
        public void FlavorTest()
        {
            // TODO unit test for the property 'Flavor'
        }
        /// <summary>
        /// Test the property 'Limit'
        /// </summary>
        [Fact]
        public void LimitTest()
        {
            // TODO unit test for the property 'Limit'
        }
        /// <summary>
        /// Test the property 'Offset'
        /// </summary>
        [Fact]
        public void OffsetTest()
        {
            // TODO unit test for the property 'Offset'
        }

    }

}
