/* 
 * Ory Kratos
 *
 * Welcome to the ORY Kratos HTTP API documentation!
 *
 * The version of the OpenAPI document: v0.5.0-alpha.1
 * 
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using Ory.Kratos.Client.Api;
using Ory.Kratos.Client.Model;
using Ory.Kratos.Client.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace Ory.Kratos.Client.Test
{
    /// <summary>
    ///  Class for testing KratosSettingsFlowMethodConfig
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class KratosSettingsFlowMethodConfigTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for KratosSettingsFlowMethodConfig
        //private KratosSettingsFlowMethodConfig instance;

        public KratosSettingsFlowMethodConfigTests()
        {
            // TODO uncomment below to create an instance of KratosSettingsFlowMethodConfig
            //instance = new KratosSettingsFlowMethodConfig();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of KratosSettingsFlowMethodConfig
        /// </summary>
        [Fact]
        public void KratosSettingsFlowMethodConfigInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOfType" KratosSettingsFlowMethodConfig
            //Assert.IsInstanceOfType<KratosSettingsFlowMethodConfig> (instance, "variable 'instance' is a KratosSettingsFlowMethodConfig");
        }


        /// <summary>
        /// Test the property 'Action'
        /// </summary>
        [Fact]
        public void ActionTest()
        {
            // TODO unit test for the property 'Action'
        }
        /// <summary>
        /// Test the property 'Fields'
        /// </summary>
        [Fact]
        public void FieldsTest()
        {
            // TODO unit test for the property 'Fields'
        }
        /// <summary>
        /// Test the property 'Messages'
        /// </summary>
        [Fact]
        public void MessagesTest()
        {
            // TODO unit test for the property 'Messages'
        }
        /// <summary>
        /// Test the property 'Method'
        /// </summary>
        [Fact]
        public void MethodTest()
        {
            // TODO unit test for the property 'Method'
        }

    }

}
