/*
 * Ory Identities API
 *
 * This is the API specification for Ory Identities with features such as registration, login, recovery, account verification, profile settings, password reset, identity management, session management, email and sms delivery, and more. 
 *
 * The version of the OpenAPI document: v1.3.6-alpha.1
 * Contact: office@ory.sh
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using Ory.Kratos.Client.Model;
using Ory.Kratos.Client.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace Ory.Kratos.Client.Test.Model
{
    /// <summary>
    ///  Class for testing KratosLoginFlowState
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class KratosLoginFlowStateTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for KratosLoginFlowState
        //private KratosLoginFlowState instance;

        public KratosLoginFlowStateTests()
        {
            // TODO uncomment below to create an instance of KratosLoginFlowState
            //instance = new KratosLoginFlowState();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of KratosLoginFlowState
        /// </summary>
        [Fact]
        public void KratosLoginFlowStateInstanceTest()
        {
            // TODO uncomment below to test "IsType" KratosLoginFlowState
            //Assert.IsType<KratosLoginFlowState>(instance);
        }
    }
}
