=begin
#Ory Hydra API

#Documentation for all of Ory Hydra's APIs. 

The version of the OpenAPI document: v2.1.0
Contact: hi@ory.sh
Generated by: https://openapi-generator.tech
OpenAPI Generator version: 6.0.1

=end

require 'spec_helper'
require 'json'
require 'date'

# Unit tests for OryHydraClient::HealthNotReadyStatus
# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate
describe OryHydraClient::HealthNotReadyStatus do
  let(:instance) { OryHydraClient::HealthNotReadyStatus.new }

  describe 'test an instance of HealthNotReadyStatus' do
    it 'should create an instance of HealthNotReadyStatus' do
      expect(instance).to be_instance_of(OryHydraClient::HealthNotReadyStatus)
    end
  end
  describe 'test attribute "errors"' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

end
