=begin
#ORY Hydra

#Welcome to the ORY Hydra HTTP API documentation. You will find documentation for all HTTP APIs here.

The version of the OpenAPI document: 1.8.0.pre1

Generated by: https://openapi-generator.tech
OpenAPI Generator version: 4.3.1

=end

module OryHydraClient
  VERSION = '1.8.0.pre1'
end
