//
// UpdateVerificationFlowBody.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

/** Update Verification Flow Request Body */
public enum UpdateVerificationFlowBody: Codable, JSONEncodable, Hashable {
    case typeUpdateVerificationFlowWithCodeMethod(UpdateVerificationFlowWithCodeMethod)
    case typeUpdateVerificationFlowWithLinkMethod(UpdateVerificationFlowWithLinkMethod)

    public func encode(to encoder: Encoder) throws {
        var container = encoder.singleValueContainer()
        switch self {
        case .typeUpdateVerificationFlowWithCodeMethod(let value):
            try container.encode(value)
        case .typeUpdateVerificationFlowWithLinkMethod(let value):
            try container.encode(value)
        }
    }

    public init(from decoder: Decoder) throws {
        let container = try decoder.singleValueContainer()
        if let value = try? container.decode(UpdateVerificationFlowWithCodeMethod.self) {
            self = .typeUpdateVerificationFlowWithCodeMethod(value)
        } else if let value = try? container.decode(UpdateVerificationFlowWithLinkMethod.self) {
            self = .typeUpdateVerificationFlowWithLinkMethod(value)
        } else {
            throw DecodingError.typeMismatch(Self.Type.self, .init(codingPath: decoder.codingPath, debugDescription: "Unable to decode instance of UpdateVerificationFlowBody"))
        }
    }
}

